/**
 * BORGOR ARCADIA & GRAND CASINO — 50+ Games Catalog
 * Metadata and rule configurations for all betting, slot, and card games.
 */
const ARCADE_GAMES = [
  /* =========================================================================
     🃏 CARD GAMES (20 Games)
     ========================================================================= */
  {
    id: 'blackjack',
    title: 'Classic Vegas Blackjack',
    category: 'cards',
    genre: 'Table Cards',
    icon: '♠️',
    badge: '3:2 PAYOUT',
    accent: '#38bdf8',
    rtp: '99.5%',
    maxWin: '2.5x',
    blurb: 'Vegas Strip 21 with Hit, Stand, Double Down, Split, and Insurance. Dealer stands on all 17s.',
    tags: ['Hit / Stand', 'Double Down', 'Split Pairs', 'Dealer on 17'],
    type: 'blackjack'
  },
  {
    id: 'single_deck_bj',
    title: 'Single Deck High Roller',
    category: 'cards',
    genre: 'High Roller Cards',
    icon: '💎',
    badge: 'SINGLE DECK',
    accent: '#fde047',
    rtp: '99.8%',
    maxWin: '2.5x',
    blurb: 'Pure 52-card deck blackjack with lowest house edge. Perfect for card counting and strategy purists.',
    tags: ['52-Card Shoe', 'Peek on 10/A', 'Double Any 2', 'Low Edge'],
    type: 'single_deck_bj'
  },
  {
    id: 'pontoon',
    title: 'Pontoon 21',
    category: 'cards',
    genre: 'British Cards',
    icon: '🎩',
    badge: '2:1 PONTOON',
    accent: '#a855f7',
    rtp: '99.6%',
    maxWin: '3x',
    blurb: 'British blackjack. Pontoon and 5-Card Trick both pay 2:1. Twist, Stick, and Buy bets.',
    tags: ['5-Card Trick', 'Buy / Twist', 'Dealer Wins Ties', '2:1 Pays'],
    type: 'pontoon'
  },
  {
    id: 'spanish21',
    title: 'Spanish 21',
    category: 'cards',
    genre: 'Specialty Cards',
    icon: '🇪🇸',
    badge: 'NO 10s BONUS',
    accent: '#ef4444',
    rtp: '99.4%',
    maxWin: '5x',
    blurb: 'Played with Spanish decks (all 10s removed). Player 21 always wins, plus bonus payouts for 6-7-8 and 7-7-7.',
    tags: ['Player 21 Wins', '6-7-8 Bonus', 'Double on Any', 'Match Dealer'],
    type: 'spanish21'
  },
  {
    id: 'baccarat',
    title: 'Baccarat Squeeze',
    category: 'cards',
    genre: 'Casino Classic',
    icon: '👑',
    badge: 'VIP SQUEEZE',
    accent: '#10b981',
    rtp: '98.9%',
    maxWin: '12x',
    blurb: 'High-stakes Punto Banco. Bet Player (1:1), Banker (0.95:1), Tie (8:1), or Banker/Player Pair (11:1).',
    tags: ['Player / Banker', '8:1 Tie', 'Pair Sidebets', 'Third Card Rule'],
    type: 'baccarat'
  },
  {
    id: 'dragon_baccarat',
    title: 'Dragon 7 Baccarat',
    category: 'cards',
    genre: 'No-Commission Table',
    icon: '🐉',
    badge: '40:1 DRAGON',
    accent: '#f97316',
    rtp: '98.8%',
    maxWin: '41x',
    blurb: 'Commission-free Baccarat. Banker winning on 3-card 7 triggers the massive 40:1 Dragon 7 jackpot!',
    tags: ['0% Commission', '40:1 Dragon 7', 'Panda 8 (25:1)', 'Fast Squeeze'],
    type: 'dragon_baccarat'
  },
  {
    id: 'holdem_heads_up',
    title: "Texas Hold'em Heads-Up",
    category: 'cards',
    genre: 'Poker Showdown',
    icon: '🃏',
    badge: '1v1 POKER',
    accent: '#06b6d4',
    rtp: '98.5%',
    maxWin: '10x',
    blurb: 'Heads-up poker duel against the Cyber Dealer. Pre-flop, Flop, Turn, and River betting with authentic hand rankings.',
    tags: ['Pre-Flop / River', 'Call / Raise / Fold', 'Hand Hierarchy', 'All-In Showdown'],
    type: 'holdem_heads_up'
  },
  {
    id: 'three_card_poker',
    title: 'Three Card Poker',
    category: 'cards',
    genre: 'Fast Poker',
    icon: '🔺',
    badge: 'PAIR PLUS 40:1',
    accent: '#ec4899',
    rtp: '97.6%',
    maxWin: '41x',
    blurb: 'Two games in one: Ante-Play against dealer (qualifies with Queen high) and Pair Plus side bet paying up to 40:1.',
    tags: ['Ante & Play', 'Pair Plus', 'Straight Flush', 'Dealer Queen High'],
    type: 'three_card_poker'
  },
  {
    id: 'caribbean_stud',
    title: 'Caribbean Stud Poker',
    category: 'cards',
    genre: 'Island Poker',
    icon: '🌴',
    badge: '100:1 ROYAL',
    accent: '#14b8a6',
    rtp: '97.2%',
    maxWin: '101x',
    blurb: '5-card stud against dealer. Dealer must have Ace-King or better. Royal Flush awards instant 100:1 bonus cashout!',
    tags: ['5-Card Stud', 'Ace-King Qualify', 'Bonus Paytable', 'Jackpot Bet'],
    type: 'caribbean_stud'
  },
  {
    id: 'casino_war',
    title: 'Casino War',
    category: 'cards',
    genre: 'High Card Battle',
    icon: '⚔️',
    badge: 'WAR OR SURRENDER',
    accent: '#e11d48',
    rtp: '97.3%',
    maxWin: '3x',
    blurb: 'Simplest, most intense card game in the casino. Higher card wins. On a tie, Go to War with double stake or surrender half!',
    tags: ['High Card Wins', 'Go to War!', 'Double Down', 'Tie Bonus 10:1'],
    type: 'casino_war'
  },
  {
    id: 'dragon_tiger',
    title: 'Dragon Tiger Showdown',
    category: 'cards',
    genre: 'Asian Two-Card',
    icon: '🐅',
    badge: '50:1 SUITED TIE',
    accent: '#d97706',
    rtp: '96.3%',
    maxWin: '51x',
    blurb: 'Two cards dealt: one Dragon, one Tiger. Highest rank wins (King high, Ace low). Suited Tie pays massive 50:1!',
    tags: ['Dragon / Tiger', 'Instant Action', '8:1 Tie', '50:1 Suited Tie'],
    type: 'dragon_tiger'
  },
  {
    id: 'red_dog',
    title: 'Red Dog Spread Poker',
    category: 'cards',
    genre: 'Spread Betting',
    icon: '🐕',
    badge: '5:1 SPREAD',
    accent: '#f43f5e',
    rtp: '97.0%',
    maxWin: '6x',
    blurb: 'Dealer draws two cards. Bet on whether the third card falls numerically between them! Tighter spread pays higher.',
    tags: ['Spread Odds', 'Consecutive Push', 'Pair Showdown', 'Double Bet'],
    type: 'red_dog'
  },
  {
    id: 'andar_bahar',
    title: 'Andar Bahar',
    category: 'cards',
    genre: 'Indian Tradition',
    icon: '🪔',
    badge: 'INSIDE / OUTSIDE',
    accent: '#8b5cf6',
    rtp: '97.8%',
    maxWin: '2x',
    blurb: 'A Joker card is dealt to the table. Will a card of the same face value land first on Andar (Inside) or Bahar (Outside)?',
    tags: ['Joker Match', 'Andar (0.9:1)', 'Bahar (1:1)', 'Rapid Deal'],
    type: 'andar_bahar'
  },
  {
    id: 'teen_patti',
    title: 'Teen Patti 3-Card',
    category: 'cards',
    genre: 'Desi Poker',
    icon: '🪙',
    badge: 'TRAIL 10:1',
    accent: '#eab308',
    rtp: '97.4%',
    maxWin: '11x',
    blurb: 'Indian 3-card poker showdown. Chaal (Bet) or Pack (Fold). Trail (Three of a kind) crushes Pure Sequence and Flush.',
    tags: ['Trail / Trio', 'Pure Sequence', 'Chaal & Pack', 'Side Show'],
    type: 'teen_patti'
  },
  {
    id: 'hilo_cards',
    title: 'Hi-Lo Card Runner',
    category: 'cards',
    genre: 'Compounding Ladder',
    icon: '📈',
    badge: 'INFINITE LADDER',
    accent: '#3b82f6',
    rtp: '98.0%',
    maxWin: '500x',
    blurb: 'Guess whether the next card is Higher or Lower. Each correct prediction multiplies your pot. Cash out anytime!',
    tags: ['Higher / Lower', 'Cashout Anytime', 'Compounding Pot', 'Streak Multiplier'],
    type: 'hilo_cards'
  },
  {
    id: 'vp_jacks',
    title: 'Video Poker: Jacks or Better',
    category: 'cards',
    genre: '5-Card Draw',
    icon: '🎰',
    badge: '800:1 ROYAL',
    accent: '#0284c7',
    rtp: '99.5%',
    maxWin: '801x',
    blurb: 'The gold standard of video poker. Hold winning cards and redraw. Pair of Jacks or better pays, Royal Flush pays 800x!',
    tags: ['Jacks or Better', 'Hold & Draw', 'Full Pay 9/6', '800x Royal Flush'],
    type: 'vp_jacks'
  },
  {
    id: 'vp_deuces',
    title: 'Video Poker: Deuces Wild',
    category: 'cards',
    genre: 'Wild Card Draw',
    icon: '🃏',
    badge: '4 DEUCES 200:1',
    accent: '#10b981',
    rtp: '98.9%',
    maxWin: '801x',
    blurb: 'All four 2s are Wild cards! Easily hit 5 of a Kind, Wild Royals, and 4 Deuces with explosive high-hand frequencies.',
    tags: ['2s Are Wild', '5 of a Kind', 'Wild Royal Flush', '4 Deuces Jackpot'],
    type: 'vp_deuces'
  },
  {
    id: 'vp_joker',
    title: 'Video Poker: Joker Poker',
    category: 'cards',
    genre: '53-Card Deck',
    icon: '🤡',
    badge: 'JOKER WILD',
    accent: '#d946ef',
    rtp: '98.6%',
    maxWin: '801x',
    blurb: 'Played with a 53-card deck containing the Joker Wild. Kings or Better min payout, Sequential Royal, and 5 of a Kind.',
    tags: ['53 Cards', 'Kings or Better', 'Joker Wild', 'Sequential Royal'],
    type: 'vp_joker'
  },
  {
    id: 'pai_gow_poker',
    title: 'Pai Gow Poker',
    category: 'cards',
    genre: 'Two-Hand Split',
    icon: '🀄',
    badge: 'HIGH / LOW HAND',
    accent: '#f59e0b',
    rtp: '97.3%',
    maxWin: '2x',
    blurb: '7 cards dealt. Split them into a 5-card High hand and a 2-card Low hand. Both hands must beat the dealer to win!',
    tags: ['5-Card & 2-Card', 'Dragon Hand', 'Push on Split', 'Joker Semi-Wild'],
    type: 'pai_gow_poker'
  },
  {
    id: 'tongits_blitz',
    title: 'Tongits Blitz Showdown',
    category: 'cards',
    genre: 'Pinoy Rummy Betting',
    icon: '🇵🇭',
    badge: 'PINOY CLASSIC',
    accent: '#e11d48',
    rtp: '98.2%',
    maxWin: '5x',
    blurb: 'Filipino 3-player rummy duel! Form melds (straight flushes & triples), Sapaw onto opponent cards, call Fight (Tawag), or declare Tongits!',
    tags: ['Meld & Sapaw', 'Tawag / Fight', 'Tongits Bonus', 'Burn Penalty'],
    type: 'tongits_blitz'
  },

  /* =========================================================================
     🎲 BETTING & TABLE GAMES (16 Games)
     ========================================================================= */
  {
    id: 'crash',
    title: 'Aviator Crash Rocket',
    category: 'betting',
    genre: 'Realtime Curve',
    icon: '🚀',
    badge: '1000x ACCELERATION',
    accent: '#ef4444',
    rtp: '97.0%',
    maxWin: '1000x',
    blurb: 'Multiplier lifts off at 1.00x and accelerates exponentially! Cash out before the rocket crashes to lock in massive wins.',
    tags: ['Realtime Graph', 'Auto-Cashout', '1000x Ceiling', 'Provably Fair'],
    type: 'crash'
  },
  {
    id: 'plinko',
    title: 'Plinko Cyber Drop',
    category: 'betting',
    genre: 'Verlet Physics',
    icon: '🟢',
    badge: '1000x BUCKET',
    accent: '#10b981',
    rtp: '98.5%',
    maxWin: '1000x',
    blurb: 'Drop cyber orbs through a peg pyramid with real bounce physics. Configurable 8, 12, or 16 rows and Low/Med/High volatility.',
    tags: ['Real Elastic Pegs', '8-16 Rows', 'Low/Med/High Risk', 'Multi-Drop Mode'],
    type: 'plinko'
  },
  {
    id: 'mines',
    title: 'Diamond Minesweeper',
    category: 'betting',
    genre: 'Grid Multiplier',
    icon: '💎',
    badge: '24 MINES MAX',
    accent: '#00f2fe',
    rtp: '98.0%',
    maxWin: '500x',
    blurb: '5x5 cyber vault grid. Choose 1 to 24 mines. Flip tiles to reveal glowing diamonds and raise your cashout multiplier. Avoid the bomb!',
    tags: ['5x5 Vault', 'Custom Mine Count', 'Cashout Anytime', 'Exponential Multipliers'],
    type: 'mines'
  },
  {
    id: 'dice',
    title: 'Cyber Dice Over / Under',
    category: 'betting',
    genre: 'Provable RNG',
    icon: '🎲',
    badge: '990x ROLL',
    accent: '#fde047',
    rtp: '99.0%',
    maxWin: '990x',
    blurb: 'Set your target number from 1 to 98 and choose Roll Over or Roll Under. Live win probability and dynamic multiplier calculation.',
    tags: ['0.01 - 99.99 Roll', 'Over / Under', 'Dynamic Multiplier', 'Instant Bet'],
    type: 'dice'
  },
  {
    id: 'color_game',
    title: 'Perya Color Game',
    category: 'betting',
    genre: 'Fiesta Carnival',
    icon: '🎪',
    badge: '3-CUBE DROP',
    accent: '#f43f5e',
    rtp: '97.2%',
    maxWin: '4x',
    blurb: 'The undisputed Philippine carnival classic! Bet on Red, Yellow, Blue, Green, White, and Pink. 3 wooden cubes drop from the chute.',
    tags: ['6 Perya Colors', '1:1 Single Match', '2:1 Double Match', '3:1 Triple Match'],
    type: 'color_game'
  },
  {
    id: 'roulette_euro',
    title: 'European Roulette 37',
    category: 'betting',
    genre: 'Classic Wheel',
    icon: '🎡',
    badge: 'SINGLE ZERO (2.7% EDGE)',
    accent: '#e11d48',
    rtp: '97.3%',
    maxWin: '36x',
    blurb: 'Authentic 37-pocket European roulette wheel (0-36). Bet Red/Black, Even/Odd, Dozens, Columns, Splits, and 35:1 Straight-Up numbers.',
    tags: ['Single Zero 0', '35:1 Straight Up', 'Red / Black', 'Dozens & Streets'],
    type: 'roulette_euro'
  },
  {
    id: 'roulette_us',
    title: 'American Roulette (00)',
    category: 'betting',
    genre: 'Vegas Wheel',
    icon: '🎰',
    badge: 'DOUBLE ZERO',
    accent: '#2563eb',
    rtp: '94.7%',
    maxWin: '36x',
    blurb: 'Classic Las Vegas 38-pocket roulette featuring both 0 and 00 green pockets with full inside and outside racetrack betting.',
    tags: ['0 & 00 Pockets', 'Basket Bet', 'Racetrack Betting', '35:1 Payout'],
    type: 'roulette_us'
  },
  {
    id: 'sicbo',
    title: 'Sic Bo Cyber Shaker',
    category: 'betting',
    genre: 'Ancient Dice',
    icon: '🏮',
    badge: '180:1 TRIPLE',
    accent: '#ea580c',
    rtp: '97.2%',
    maxWin: '181x',
    blurb: 'Three dice tumbled inside an electrified glass shaker. Bet Small/Big (1:1), Total Sums (6x to 60x), Specific Doubles, and 180:1 Triples!',
    tags: ['Big / Small (1:1)', 'Specific Triple (180:1)', 'Any Triple (30:1)', 'Dice Sums'],
    type: 'sicbo'
  },
  {
    id: 'craps',
    title: 'Craps Street Dice',
    category: 'betting',
    genre: 'Dice Table',
    icon: '🎲',
    badge: 'PASS / COME',
    accent: '#16a34a',
    rtp: '98.6%',
    maxWin: '31x',
    blurb: 'Fast-paced street and casino craps. Bet Pass Line, Don’t Pass, Field (2 & 12 pay 2x/3x), Any 7, and Hardways (Hard 4, 6, 8, 10).',
    tags: ['Come-Out Roll', 'Point Established', 'Field Bet', 'Hardways 9:1'],
    type: 'craps'
  },
  {
    id: 'coinflip',
    title: 'Coin Flip Streak',
    category: 'betting',
    genre: 'Streak Multiplier',
    icon: '🪙',
    badge: '64x STREAK',
    accent: '#facc15',
    rtp: '98.0%',
    maxWin: '64x',
    blurb: 'Choose Heads or Tails with true 50/50 odds. Chain consecutive correct calls together to double your winnings up to 64x or cash out!',
    tags: ['True 50/50', 'Chain Multiplier', 'Cashout Anytime', 'Instant 3D Flip'],
    type: 'coinflip'
  },
  {
    id: 'wheel',
    title: 'Wheel of Fortune 54',
    category: 'betting',
    genre: 'Money Wheel',
    icon: '🎯',
    badge: 'MEGA 40x + RESPIN',
    accent: '#c084fc',
    rtp: '96.5%',
    maxWin: '280x',
    blurb: '54-segment neon spinning money wheel. Place chips on 1x, 2x, 5x, 10x, 20x, 40x, or hit the 2x/7x Multiplier Respin multiplier triggers!',
    tags: ['54 Segments', '2x/7x Respin Multiplier', '40x Megasegment', 'Flapper Pegs'],
    type: 'wheel'
  },
  {
    id: 'keno',
    title: 'Keno Mega 80',
    category: 'betting',
    genre: 'Lottery Draw',
    icon: '🎱',
    badge: '10,000x JACKPOT',
    accent: '#06b6d4',
    rtp: '95.5%',
    maxWin: '10000x',
    blurb: 'Pick 1 to 10 lucky numbers from 1 to 80. The cyber hopper draws 20 golden balls. Match 10 out of 10 for the 10,000x grand prize!',
    tags: ['80-Number Board', 'Pick 1-10', '20-Ball Draw', 'Dynamic Paytable'],
    type: 'keno'
  },
  {
    id: 'horse_derby',
    title: 'Cyber Horse Sprint Derby',
    category: 'betting',
    genre: 'Racing Sim',
    icon: '🏇',
    badge: '6-LANE DERBY',
    accent: '#84cc16',
    rtp: '96.8%',
    maxWin: '25x',
    blurb: '6 cyber steeds dash down a neon synthetic turf! Inspect form ratings, track condition, and place bets on Win (1st), Place, or Show.',
    tags: ['6 Cyber Steeds', 'Dynamic Odds', 'Realtime Sprint Canvas', 'Photo Finish'],
    type: 'horse_derby'
  },
  {
    id: 'scratch_gold',
    title: 'Scratch & Win: Neon Gold',
    category: 'betting',
    genre: 'Instant Win Card',
    icon: '🎫',
    badge: '500x FOIL',
    accent: '#f59e0b',
    rtp: '96.0%',
    maxWin: '500x',
    blurb: '9 holographic foil panels. Scratch panels with your mouse or finger to reveal 3 matching symbols and claim instant cash rewards!',
    tags: ['9 Foil Panels', 'Mouse / Touch Scratch', 'Match 3 to Win', 'Instant Cashout'],
    type: 'scratch_gold'
  },
  {
    id: 'limbo',
    title: 'Limbo Turbo Rocket',
    category: 'betting',
    genre: 'Instant Target',
    icon: '⚡',
    badge: '10,000x TARGET',
    accent: '#ec4899',
    rtp: '99.0%',
    maxWin: '10000x',
    blurb: 'Set any target multiplier from 1.01x up to 10,000x. The rocket launches instantly—if the result is equal or higher, you win instantly!',
    tags: ['Instant Roll', 'Target 1.01x-10k', 'Sub-second Rounds', '99% RTP'],
    type: 'limbo'
  },
  {
    id: 'tower_climb',
    title: 'Spire Tower Climb',
    category: 'betting',
    genre: 'Step-by-Step Risk',
    icon: '🏰',
    badge: '10-FLOOR SPIRE',
    accent: '#6366f1',
    rtp: '97.5%',
    maxWin: '100x',
    blurb: 'Climb a 10-story cyber spire. Each floor has 3 doors: 2 lead to stairs up with growing multipliers, 1 collapses into a trap. Cash out anytime!',
    tags: ['10 Floors', '2 Safe / 1 Trap', 'Cashout Anytime', '100x Top Floor'],
    type: 'tower_climb'
  },
  {
    id: 'perya_roulette',
    title: 'Perya Billiard Table Roulette',
    category: 'betting',
    genre: 'Tabletop Arcade',
    icon: '🎱',
    badge: '28-TILE ARENA',
    accent: '#f59e0b',
    rtp: '97.5%',
    maxWin: '25x',
    blurb: 'Authentic 28-tile peryahan billiard roulette. 30s betting timer, 15s runner spin with reverse rotation, 8-ball odds, and mystery bonuses.',
    tags: ['28 Perya Tiles', '8-Ball Odds', 'Room Multiplayer', 'Soundtrack Engine'],
    directUrl: '/roulette/'
  },
  {
    id: 'aqua_fishrace',
    title: 'Cyber Aqua Fish Race',
    category: 'betting',
    genre: 'Aquatic Derby',
    icon: '🐟',
    badge: '8-SPECIES DERBY',
    accent: '#06b6d4',
    rtp: '96.5%',
    maxWin: '20x',
    blurb: '8-lane cybernetic fish sprint with real-time sinusoidal spine physics, dynamic odds, and JTrash room synchronization.',
    tags: ['8 Fish Lanes', 'Sine Swimming Physics', '30s Betting Timer', 'Multiplayer Sync'],
    directUrl: '/fishrace/'
  },

  /* =========================================================================
     🎰 SLOT MACHINES (16 Games)
     ========================================================================= */
  {
    id: 'slots_borgor',
    title: 'Gates of Borgor',
    category: 'slots',
    genre: 'Scatter Pay',
    icon: '🍔',
    badge: '500x BOMBS',
    accent: '#f5b041',
    rtp: '96.5%',
    maxWin: '5000x',
    blurb: 'Vegas-grade 6x5 scatter machine. Multiplier bombs up to 500x, Diamond Vaults crackdown, free spins, and dynamic 40% balance feature buy.',
    tags: ['6x5 Grid', 'Diamond Vault', '500x Bombs', 'Feature Buy'],
    directUrl: '/slots/?variant=borgor'
  },
  {
    id: 'slots_cyber',
    title: 'Cyber Overdrive',
    category: 'slots',
    genre: 'Cyberpunk Scatter',
    icon: '⚡',
    badge: '1000x OVERCLOCK',
    accent: '#00f2fe',
    rtp: '96.5%',
    maxWin: '5000x',
    blurb: 'High-octane 6x5 cyberpunk tumble machine. Neural ICE Breach bonus hack, Overclock glitch multipliers up to 1000x, and cyber free spins.',
    tags: ['ICE Breach Hack', '1000x Overclock', 'Glitch Cascade', 'Tokyo 2099'],
    directUrl: '/slots/?variant=cyber'
  },
  {
    id: 'slots_candy',
    title: 'Sugar Sweet Frenzy',
    category: 'slots',
    genre: 'Candy Pop Scatter',
    icon: '🍭',
    badge: 'PINATA BASH',
    accent: '#f472b6',
    rtp: '96.5%',
    maxWin: '5000x',
    blurb: 'Candy-coated 6x5 cascade wonderland. Sugar Bomb Pinata Bash with sticky multiplier spots, jawbreaker multipliers up to 500x, and sweet re-spins.',
    tags: ['Pinata Bash', 'Sticky Spots', 'Sweet Cascades', 'Sugar Rush'],
    directUrl: '/slots/?variant=candy'
  },
  {
    id: 'slots_anubis',
    title: 'Tomb of Anubis',
    category: 'slots',
    genre: 'Egyptian Relic',
    icon: '⚱️',
    badge: 'CHAMBER OF RA',
    accent: '#f59e0b',
    rtp: '96.5%',
    maxWin: '5000x',
    blurb: 'Mystic Egyptian 6x5 relic tumbler. Sarcophagus Chamber of Ra bonus cashout, Sun Disc multipliers up to 500x, and Eye of Horus free spins.',
    tags: ['Chamber of Ra', 'Ankh Bounties', '500x Sun Discs', 'Pharaoh Curse'],
    directUrl: '/slots/?variant=anubis'
  },
  {
    id: 'slot_vegas777',
    title: 'Classic Vegas 777',
    category: 'slots',
    genre: 'Mechanical 3-Reel',
    icon: '🎰',
    badge: '1000x TRIPLE 7',
    accent: '#ef4444',
    rtp: '96.8%',
    maxWin: '1000x',
    blurb: 'Authentic 3-reel, 5-payline mechanical slot machine. Cherries, Single/Double/Triple Bars, and Blazing Red 7s for the 1000x Jackpot line.',
    tags: ['3 Reels / 5 Lines', 'Bars & Cherries', 'Blazing Red 7s', 'Retro Lever Sound'],
    type: 'slot_vegas777'
  },
  {
    id: 'slot_fruit_fiesta',
    title: 'Fruit Fiesta Deluxe',
    category: 'slots',
    genre: '25-Line Fruit',
    icon: '🍉',
    badge: 'EXPANDING WILDS',
    accent: '#10b981',
    rtp: '96.3%',
    maxWin: '2500x',
    blurb: '5-reel, 25-payline colorful fruit fiesta. Expanding Wild Watermelons cover entire reels, Golden Star scatters trigger 15 Free Games.',
    tags: ['5 Reels / 25 Lines', 'Expanding Wilds', 'Star Scatters', '15 Free Spins'],
    type: 'slot_fruit_fiesta'
  },
  {
    id: 'slot_dragon_hold',
    title: 'Mega Dragon Hold & Win',
    category: 'slots',
    genre: 'Hold & Win Jackpot',
    icon: '🐲',
    badge: 'GRAND 2000x',
    accent: '#f59e0b',
    rtp: '96.4%',
    maxWin: '2000x',
    blurb: '5x4 Asian fortune reels. Land 6+ Golden Coins to trigger the Hold & Win respin round with Mini (20x), Minor (50x), Major (200x), and Grand (2000x) Jackpots!',
    tags: ['Hold & Win', '3 Respin Reset', '4 Tier Jackpots', 'Lock & Spin'],
    type: 'slot_dragon_hold'
  },
  {
    id: 'slot_buffalo',
    title: 'Buffalo Wild Stampede',
    category: 'slots',
    genre: '4096 Ways',
    icon: '🦬',
    badge: '4096 WAYS',
    accent: '#d97706',
    rtp: '96.1%',
    maxWin: '4096x',
    blurb: '6x4 reels with 4096 ways to win. Golden Buffalo symbols stack on all reels. Sunset Wilds carry 2x and 3x multipliers during Free Stampede rounds.',
    tags: ['4096 Ways', 'Stacked Buffalo', '2x/3x Wild Multipliers', 'Stampede Respins'],
    type: 'slot_buffalo'
  },
  {
    id: 'slot_book_dead',
    title: 'Book of Dead Borgor',
    category: 'slots',
    genre: 'Expanding Symbol',
    icon: '📖',
    badge: 'EXPANDING SYMBOL',
    accent: '#b45309',
    rtp: '96.2%',
    maxWin: '5000x',
    blurb: '5x3 reels, 10 paylines. 3 Golden Book scatters trigger 10 Free Spins with a randomly chosen special expanding symbol that pays on any reel!',
    tags: ['Book Scatter/Wild', 'Special Expanding Symbol', '10 Free Spins', '5000x Full Screen'],
    type: 'slot_book_dead'
  },
  {
    id: 'slot_money_cart',
    title: 'Money Cart Train Heist',
    category: 'slots',
    genre: 'Bonus Respin Cart',
    icon: '🚂',
    badge: 'COLLECTOR & SNIPER',
    accent: '#78716c',
    rtp: '96.4%',
    maxWin: '5000x',
    blurb: 'Post-apocalyptic train heist. 3 bonus symbols unlock the Cart Respin bonus round featuring Persistent Collector, Sniper, and Payer mechanics!',
    tags: ['Hold & Win Cart', 'Persistent Collector', 'Sniper Multipliers', 'Row Expander'],
    type: 'slot_money_cart'
  },
  {
    id: 'slot_mahjong',
    title: 'Mahjong Ways',
    category: 'slots',
    genre: 'Cascading Tiles',
    icon: '🀄',
    badge: '5x CASCADE MULT',
    accent: '#059669',
    rtp: '96.7%',
    maxWin: '2500x',
    blurb: '5x4 cascading Mahjong tiles. Gold-plated symbols transform into Wild Ingot symbols on cascade wins, with progressive multipliers up to 5x!',
    tags: ['Cascading Tiles', 'Gold Plated Wilds', 'Progressive Multiplier', 'Free Spins 10x'],
    type: 'slot_mahjong'
  },
  {
    id: 'slot_perya_fruit',
    title: 'Perya Fruit Box (Lucky 8)',
    category: 'slots',
    genre: 'Asian Street Arcade',
    icon: '🍎',
    badge: 'LED RUNNER BOX',
    accent: '#dc2626',
    rtp: '97.0%',
    maxWin: '100x',
    blurb: 'The legendary Asian street betting box! Bet on Apple, Orange, Mango, Bell, Watermelon, Star, 77, and Bar with a running LED square light.',
    tags: ['8 Fruit Buttons', 'Flashing LED Light', 'Bar 100:1', 'Retro 8-Bit SFX'],
    type: 'slot_perya_fruit'
  },
  {
    id: 'slot_neon_reels',
    title: 'Neon Cyber Reels',
    category: 'slots',
    genre: 'Synthwave 20-Line',
    icon: '🕶️',
    badge: 'LASER WILDS',
    accent: '#a855f7',
    rtp: '96.4%',
    maxWin: '2000x',
    blurb: '5-reel, 20-payline cyberpunk synthwave slot. Full-reel Laser Wilds shoot beams across matching rows with stacked neon cassette symbols.',
    tags: ['Laser Wilds', 'Synthwave OST', 'Cassette Stacks', 'Neon Respin'],
    type: 'slot_neon_reels'
  },
  {
    id: 'slot_aztec_gold',
    title: 'Aztec Gold Cascades',
    category: 'slots',
    genre: 'Avalanche Megagrid',
    icon: '🗿',
    badge: 'AVALANCHE 10x',
    accent: '#ca8a04',
    rtp: '96.1%',
    maxWin: '3000x',
    blurb: '6x5 cascading stone ruin reels. Winning blocks crumble in avalanches as golden totem multipliers crash down from the temple ceiling.',
    tags: ['Stone Avalanche', 'Totem Multipliers', 'Sun God Free Spins', 'Cascading Grid'],
    type: 'slot_aztec_gold'
  },
  {
    id: 'pinball',
    title: 'Cyber Pinball 3D',
    category: 'slots',
    genre: 'Arcade Physics',
    icon: '🕹️',
    badge: 'VERLET TABLE',
    accent: '#38bdf8',
    rtp: '98.0%',
    maxWin: '10x',
    blurb: 'High-speed spring plunger, dual flippers, resonant bumpers, rollover combo multipliers, and head-to-head 1v1 score match challenges.',
    tags: ['60 FPS Verlet', 'Borgor Combos', '1v1 Ref Match', 'Plunger Physics'],
    directUrl: '/pinball/'
  },
  {
    id: 'pool',
    title: 'Neon 8-Ball Pool',
    category: 'slots',
    genre: 'Billiards Sim',
    icon: '🎱',
    badge: '3D BILLIARDS',
    accent: '#10b981',
    rtp: '98.5%',
    maxWin: '10x',
    blurb: 'Realistic billiard physics with rolling friction, elastic sphere collisions, cue guide line, power meter, and 1v1 match challenges via Ref no.',
    tags: ['Real Momentum', 'Solids & Stripes', 'Ref Invite', 'Cue Guide Line'],
    directUrl: '/pool/'
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ARCADE_GAMES };
}
